#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
#  BELLA — One-time server initialisation
#  Run this ONCE on the Azure VM (e.g. via Azure Portal → Run Command).
#  After this, every  git pull  on the server works with zero manual steps.
#
#  Usage:
#    sudo bash server_init.sh [APP_DIR]
#    APP_DIR defaults to /opt/bella/dream
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

APP_DIR="${1:-/opt/bella/dream}"
ENV_FILE="/etc/bella.env"
SERVICE_FILE="/etc/systemd/system/bella.service"
SERVICE_USER="${SUDO_USER:-ubuntu}"

echo "=== BELLA Server Init ==="
echo "  App dir  : $APP_DIR"
echo "  Env file : $ENV_FILE"
echo "  Service  : bella.service"
echo ""

# ── 1. Write credential environment file ─────────────────────────────────
# Replace PLACEHOLDER values with real ones before running.
cat > "$ENV_FILE" <<'ENVEOF'
# ── Microsoft Entra ID (Azure AD SSO) ──────────────────────────────────
AAD_CLIENT_ID=REPLACE_AAD_CLIENT_ID
AAD_TENANT_ID=REPLACE_AAD_TENANT_ID
AAD_CLIENT_SECRET=REPLACE_AAD_CLIENT_SECRET

# ── Azure OpenAI ────────────────────────────────────────────────────────
AZURE_API_KEY=REPLACE_AZURE_API_KEY
AZURE_ENDPOINT=REPLACE_AZURE_ENDPOINT
AZURE_DEPLOYMENT=REPLACE_AZURE_DEPLOYMENT

# ── Claude (Azure AI Services) ──────────────────────────────────────────
ANTHROPIC_API_KEY=REPLACE_ANTHROPIC_API_KEY
CLAUDE_ENDPOINT=REPLACE_CLAUDE_ENDPOINT

# ── Grok ────────────────────────────────────────────────────────────────
GROK_ENDPOINT=REPLACE_GROK_ENDPOINT
GROK_KEY=REPLACE_GROK_KEY

# ── DeepSeek ────────────────────────────────────────────────────────────
DEEPSEEK_ENDPOINT=REPLACE_DEEPSEEK_ENDPOINT
DEEPSEEK_KEY=REPLACE_DEEPSEEK_KEY

# ── Codex ───────────────────────────────────────────────────────────────
CODEX_API_KEY=REPLACE_CODEX_API_KEY
CODEX_ENDPOINT=REPLACE_CODEX_ENDPOINT

# ── Nano ────────────────────────────────────────────────────────────────
NANO_ENDPOINT=REPLACE_NANO_ENDPOINT
NANO_KEY=REPLACE_NANO_KEY

# ── Qwen ────────────────────────────────────────────────────────────────
QWEN_ENDPOINT=REPLACE_QWEN_ENDPOINT
QWEN_FOUNDRY_KEY=REPLACE_QWEN_FOUNDRY_KEY
ENVEOF

chmod 600 "$ENV_FILE"
echo "[OK] Created $ENV_FILE"

# ── 2. Create Streamlit secrets.toml from env file ────────────────────────
SECRETS_DIR="$APP_DIR/.streamlit"
mkdir -p "$SECRETS_DIR"
cat > "$SECRETS_DIR/secrets.toml" <<TOMLEOF
# Auto-generated by server_init.sh — do not edit manually; re-run the script
AAD_CLIENT_ID     = "$(grep '^AAD_CLIENT_ID=' $ENV_FILE | cut -d= -f2-)"
AAD_TENANT_ID     = "$(grep '^AAD_TENANT_ID=' $ENV_FILE | cut -d= -f2-)"
AAD_CLIENT_SECRET = "$(grep '^AAD_CLIENT_SECRET=' $ENV_FILE | cut -d= -f2-)"
TOMLEOF
echo "[OK] Created $SECRETS_DIR/secrets.toml"

# ── 3. Create systemd service ─────────────────────────────────────────────
cat > "$SERVICE_FILE" <<SVCEOF
[Unit]
Description=BELLA — ECI Presales AI Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=$ENV_FILE
ExecStart=/usr/bin/env streamlit run app.py --server.port 8501 --server.address 0.0.0.0
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable bella
systemctl restart bella
echo "[OK] bella.service enabled and started"

# ── 4. Create git post-merge hook for zero-touch updates ─────────────────
GIT_DIR="$APP_DIR/.git"
if [ -d "$GIT_DIR" ]; then
    HOOK="$GIT_DIR/hooks/post-merge"
    cat > "$HOOK" <<'HOOKEOF'
#!/usr/bin/env bash
# Restart BELLA automatically after every git pull
systemctl restart bella
echo "bella service restarted"
HOOKEOF
    chmod +x "$HOOK"
    echo "[OK] git post-merge hook installed — service auto-restarts on git pull"
fi

echo ""
echo "=== Done! BELLA is running on port 8501 ==="
echo "    Every future 'git pull' automatically restarts the service."
